
version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/fastapi
    ports:
      - "8080:8000"
    depends_on:
      - database

  database:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - database_prod.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: